"""initial schema

Revision ID: 4cebc83d3603
Revises: 
Create Date: 2026-06-02 10:07:16.244371
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cebc83d3603'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='orgplan', native_enum=False), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('api_key',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_hashed_key'), ['hashed_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_org_id'), ['org_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('actor_kind', sa.Enum('user', 'agent', 'system', name='auditactorkind', native_enum=False), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)

    op.create_table('membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'editor', 'analyst', 'viewer', name='membershiprole', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_user_id'), ['user_id'], unique=False)

    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_randomization_unit', sa.Enum('user_id', 'session_id', 'device_id', 'account_id', name='randomizationunit', native_enum=False), nullable=False),
    sa.Column('analytics_backend', sa.Enum('duckdb', 'bigquery', 'snowflake', 'databricks', name='analyticsbackend', native_enum=False), nullable=False),
    sa.Column('event_schema', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_workspace_org_slug')
    )
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_org_id'), ['org_id'], unique=False)

    op.create_table('layer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traffic_partitions', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_layer_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_layer_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('proportion', 'mean', 'ratio', 'count', name='metrictype', native_enum=False), nullable=False),
    sa.Column('numerator', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('denominator', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('direction', sa.Enum('increase_good', 'decrease_good', name='metricdirection', native_enum=False), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('winsorize_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_metric_workspace_key')
    )
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('experiment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hypothesis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'running', 'paused', 'concluded', 'archived', name='experimentstatus', native_enum=False), nullable=False),
    sa.Column('layer_id', sa.Uuid(), nullable=True),
    sa.Column('randomization_unit', sa.Enum('user_id', 'session_id', 'device_id', 'account_id', name='randomizationunit', native_enum=False), nullable=False),
    sa.Column('allocation', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('targeting', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('ship', 'no_ship', 'iterate', 'inconclusive', name='experimentdecision', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_experiment_workspace_key')
    )
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('agent_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=True),
    sa.Column('agent_type', sa.Enum('designer', 'monitor', 'analyst', 'readout', name='agenttype', native_enum=False), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='agentrunstatus', native_enum=False), nullable=False),
    sa.Column('cost_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_org_id'), ['org_id'], unique=False)

    op.create_table('analysis_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.Enum('scheduled', 'manual', 'agent', name='analysistrigger', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='analysisstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_run_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_run_org_id'), ['org_id'], unique=False)

    op.create_table('experiment_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'secondary', 'guardrail', name='experimentmetricrole', native_enum=False), nullable=False),
    sa.Column('min_detectable_effect', sa.Float(), nullable=True),
    sa.Column('is_oec', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'metric_id', name='uq_expmetric_exp_metric')
    )
    with op.batch_alter_table('experiment_metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_metric_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_metric_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_metric_org_id'), ['org_id'], unique=False)

    op.create_table('variant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('allocation_pct', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'key', name='uq_variant_experiment_key')
    )
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variant_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_variant_org_id'), ['org_id'], unique=False)

    op.create_table('agent_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('message', 'tool_call', 'tool_result', name='agentstepkind', native_enum=False), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'seq', name='uq_agentstep_run_seq')
    )
    with op.batch_alter_table('agent_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_step_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_step_org_id'), ['org_id'], unique=False)

    op.create_table('metric_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('estimate', sa.Float(), nullable=True),
    sa.Column('abs_effect', sa.Float(), nullable=True),
    sa.Column('rel_effect', sa.Float(), nullable=True),
    sa.Column('ci_lower', sa.Float(), nullable=True),
    sa.Column('ci_upper', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('prob_to_beat_control', sa.Float(), nullable=True),
    sa.Column('expected_loss', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('std_error', sa.Float(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=False),
    sa.Column('method_detail', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'metric_id', 'variant_id', name='uq_metricresult_run_metric_variant')
    )
    with op.batch_alter_table('metric_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_result_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_result_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_result_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_result_variant_id'), ['variant_id'], unique=False)

    op.create_table('readout',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=True),
    sa.Column('author_kind', sa.Enum('agent', 'human', name='readoutauthor', native_enum=False), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision_recommendation', sa.Enum('ship', 'no_ship', 'iterate', 'inconclusive', name='experimentdecision', native_enum=False), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('body_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readout_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_readout_org_id'), ['org_id'], unique=False)

    op.create_table('srm_check',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('chi_square', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('observed', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('expected', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('is_mismatch', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('srm_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_srm_check_analysis_run_id'), ['analysis_run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_srm_check_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('srm_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_srm_check_org_id'))
        batch_op.drop_index(batch_op.f('ix_srm_check_analysis_run_id'))

    op.drop_table('srm_check')
    with op.batch_alter_table('readout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readout_org_id'))
        batch_op.drop_index(batch_op.f('ix_readout_experiment_id'))

    op.drop_table('readout')
    with op.batch_alter_table('metric_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_result_variant_id'))
        batch_op.drop_index(batch_op.f('ix_metric_result_org_id'))
        batch_op.drop_index(batch_op.f('ix_metric_result_metric_id'))
        batch_op.drop_index(batch_op.f('ix_metric_result_analysis_run_id'))

    op.drop_table('metric_result')
    with op.batch_alter_table('agent_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_step_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_step_agent_run_id'))

    op.drop_table('agent_step')
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variant_org_id'))
        batch_op.drop_index(batch_op.f('ix_variant_experiment_id'))

    op.drop_table('variant')
    with op.batch_alter_table('experiment_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_metric_org_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_metric_metric_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_metric_experiment_id'))

    op.drop_table('experiment_metric')
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_run_org_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_run_experiment_id'))

    op.drop_table('analysis_run')
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_org_id'))

    op.drop_table('agent_run')
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_org_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_key'))

    op.drop_table('experiment')
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_metric_org_id'))

    op.drop_table('metric')
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layer_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_layer_org_id'))

    op.drop_table('layer')
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_org_id'))

    op.drop_table('workspace')
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_membership_org_id'))

    op.drop_table('membership')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_hashed_key'))

    op.drop_table('api_key')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug'))

    op.drop_table('organization')
    # ### end Alembic commands ###
